name: Build subscription 

on: 
  push: 
    branches: [ "main" ] 
  workflow_dispatch: 
  
permissions:
  contents: write 
  
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps:
     - uses: actions/checkout@v4 
     
     - uses: actions/setup-python@v5
       with:
         python-version: "3.11"

     - name: Generate sub files 
       run: python generate_sub.py 
       
     - name: Commit generated files 
       uses: stefanzweifel/git-auto-commit-action@v5 
       with: 
        commit_message: "Update subscription files" 
        file_pattern: sub.txt sub_base64.txt
